version: '3'
services:
  mongodb:
    image: mongo:4.0
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb:/data/db
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis:/data/redis